version: '3'

services:
  web:
    build: .

  nginx:
    image: nginx:1.13.0
    links:
      - web:web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    command: ['nginx', '-g', 'daemon off;']
    ports:
      - 80:80
